export const darkTheme = {
  // '--fontColorDefault': '#ffffff',
  '--fontColorBtn': ' var(--fontColorDefault)',
  '--ColorDefault': '#272d33',
  '--animGlow': 'none',
  '--animBFlicker': 'none',
  '--animTFlicker': 'none',
  '--borderH': '0.2rem solid var(--fontColorDefault)',
  '--borderB': '0.1rem solid var(--fontColorDefault)',
  '--borderDaily': 'var(--fontColorDefault)',
  '--borderSearch': 'var(--fontColorDefault)',
  '--borderLists': 'var(--fontColorDefault)',
  '--borderLogout': 'var(--fontColorDefault)',
  '--borderLana': 'var(--fontColorDefault)',
};

export const lightTheme = {
  // '--fontColorDefault': '#ffffff',
  '--fontColorBtn': 'rgb(223, 90, 90)',
  '--ColorDefault': '#292929',
  '--animGlow': 'glow 4s linear infinite',
  '--animBFlicker': 'border-flicker 2s linear infinite',
  '--animTFlicker': 'text-flicker 3s linear infinite',
  '--borderH': '0.2rem solid #1086e8',
  '--borderB': '0.1rem solid #1086e8',
  '--borderDaily': '#e73c7e',
  '--borderSearch': '#393',
  '--borderLists': ' #07b39b',
  '--borderLogout': '#ee7752',
  "--borderLana" : "#a32ead",
};
